var React = require('react');
var Select = require('react-select');

var Fighter = React.createClass({
  updateValue (newValue) {
    if (newValue === undefined) newValue = null;
    this.setState({
      selectValue: newValue
    });
    console.log('State changed to ' + JSON.stringify(newValue.value));
  },
  getInitialState () {
    return {
      disabled: false,
      searchable: this.props.searchable,
      selectValue: null,
      clearable: true,
    };
  },
  render: function() {
    var options = [
      { value: '3-D Man', label: '3-D Man'},
      { value: 'A-Bomb', label: 'A-Bomb'},
      { value: 'A.I.M.', label: 'A.I.M.'},
      { value: 'Aaron Stack', label: 'Aaron Stack'},
      { value: 'Abomination', label: 'Abomination'},
      { value: 'Absorbing Man', label: 'Absorbing Man'},
      { value: 'Abyss', label: 'Abyss'},
      { value: 'Adam Destine', label: 'Adam Destine'},
      { value: 'Adam Warlock', label: 'Adam Warlock'},
      { value: 'Aegis', label: 'Aegis'},
      { value: 'Agent Brand', label: 'Agent Brand'},
      { value: 'Agent X', label: 'Agent X'},
      { value: 'Agent Zero', label: 'Agent Zero'},
      { value: 'Agents of Atlas', label: 'Agents of Atlas'},
      { value: 'Aginar', label: 'Aginar'},
      { value: 'Air-Walker', label: 'Air-Walker'},
      { value: 'Ajak', label: 'Ajak'},
      { value: 'Ajaxis', label: 'Ajaxis'},
      { value: 'Akemi', label: 'Akemi'},
      { value: 'Alain', label: 'Alain'},
      { value: 'Albert Cleary', label: 'Albert Cleary'},
      { value: 'Albion', label: 'Albion'},
      { value: 'Alex Power', label: 'Alex Power'},
      { value: 'Alex Wilder', label: 'Alex Wilder'},
      { value: 'Alexa Mendez', label: 'Alexa Mendez'},
      { value: 'Alexander Pierce', label: 'Alexander Pierce'},
      { value: 'Alice', label: 'Alice'},
      { value: 'Alicia Masters', label: 'Alicia Masters'},
      { value: 'Alpha Flight', label: 'Alpha Flight'},
      { value: 'Alvin Maker', label: 'Alvin Maker'},
      { value: 'Amadeus Cho', label: 'Amadeus Cho'},
      { value: 'Amanda Sefton', label: 'Amanda Sefton'},
      { value: 'Amazoness', label: 'Amazoness'},
      { value: 'American Eagle', label: 'American Eagle'},
      { value: 'Amiko', label: 'Amiko'},
      { value: 'Amora', label: 'Amora'},
      { value: 'Amphibian', label: 'Amphibian'},
      { value: 'Amun', label: 'Amun'},
      { value: 'Ancient One', label: 'Ancient One'},
      { value: 'Angel', label: 'Angel'},
      { value: 'Angela', label: 'Angela'},
      { value: 'Anita Blake', label: 'Anita Blake'},
      { value: 'Anne Marie Hoag', label: 'Anne Marie Hoag'},
      { value: 'Annihilus', label: 'Annihilus'},
      { value: 'Anole', label: 'Anole'},
      { value: 'Ant-Man', label: 'Ant-Man'},
      { value: 'Anthem', label: 'Anthem'},
      { value: 'Apocalypse', label: 'Apocalypse'},
      { value: 'Aqueduct', label: 'Aqueduct'},
      { value: 'Arachne', label: 'Arachne'},
      { value: 'Araٌa', label: 'Araٌa'},
      { value: 'Arcade', label: 'Arcade'},
      { value: 'Arcana', label: 'Arcana'},
      { value: 'Archangel', label: 'Archangel'},
      { value: 'Arclight', label: 'Arclight'},
      { value: 'Ares', label: 'Ares'},
      { value: 'Argent', label: 'Argent'},
      { value: 'Armadillo', label: 'Armadillo'},
      { value: 'Armor', label: 'Armor'},
      { value: 'Armory', label: 'Armory'},
      { value: 'Arnim Zola', label: 'Arnim Zola'},
      { value: 'Arsenic', label: 'Arsenic'},
      { value: 'Artiee', label: 'Artiee'},
      { value: 'Asgardian', label: 'Asgardian'},
      { value: 'Askew-Tronics', label: 'Askew-Tronics'},
      { value: 'Asylum', label: 'Asylum'},
      { value: 'Atlas', label: 'Atlas'},
      { value: 'Aurora', label: 'Aurora'},
      { value: 'Avalanche', label: 'Avalanche'},
      { value: 'Avengers', label: 'Avengers'},
      { value: 'Azazel', label: 'Azazel'},
      { value: 'Banshee', label: 'Banshee'},
      { value: 'Baron Strucker', label: 'Baron Strucker'},
      { value: 'Baron Zemo', label: 'Baron Zemo'},
      { value: 'Baroness S\'Bak', label: 'Baroness S\'Bak'},
      { value: 'Barracuda', label: 'Barracuda'},
      { value: 'Bart Rozum', label: 'Bart Rozum'},
      { value: 'Bastion', label: 'Bastion'},
      { value: 'Batroc the Leaper', label: 'Batroc the Leaper'},
      { value: 'Battering Ram', label: 'Battering Ram'},
      { value: 'Beak', label: 'Beak'},
      { value: 'Beast', label: 'Beast'},
      { value: 'Becatron', label: 'Becatron'},
      { value: 'Bedlam', label: 'Bedlam'},
      { value: 'Beef', label: 'Beef'},
      { value: 'Beetle', label: 'Beetle'},
      { value: 'Ben Grimm', label: 'Ben Grimm'},
      { value: 'Ben Parker', label: 'Ben Parker'},
      { value: 'Ben Reilly', label: 'Ben Reilly'},
      { value: 'Ben Urich', label: 'Ben Urich'},
      { value: 'Bengal', label: 'Bengal'},
      { value: 'Beta-Ray Bill', label: 'Beta-Ray Bill'},
      { value: 'Betty Brant', label: 'Betty Brant'},
      { value: 'Betty Ross', label: 'Betty Ross'},
      { value: 'Beyonder', label: 'Beyonder'},
      { value: 'Bi-Beast', label: 'Bi-Beast'},
      { value: 'Big Bertha', label: 'Big Bertha'},
      { value: 'Big Wheel', label: 'Big Wheel'},
      { value: 'Bill Hollister', label: 'Bill Hollister'},
      { value: 'Bishop', label: 'Bishop'},
      { value: 'Black Bird', label: 'Black Bird'},
      { value: 'Black Bolt', label: 'Black Bolt'},
      { value: 'Black Cat', label: 'Black Cat'},
      { value: 'Black Crow', label: 'Black Crow'},
      { value: 'Black Knight', label: 'Black Knight'},
      { value: 'Black Panther', label: 'Black Panther'},
      { value: 'Black Queen', label: 'Black Queen'},
      { value: 'Black Tarantula', label: 'Black Tarantula'},
      { value: 'Black Tom', label: 'Black Tom'},
      { value: 'Black Widow', label: 'Black Widow'},
      { value: 'Black Widow/Natasha Romanoff', label: 'Black Widow/Natasha Romanoff'},
      { value: 'Blackheart', label: 'Blackheart'},
      { value: 'Blacklash', label: 'Blacklash'},
      { value: 'Blackout', label: 'Blackout'},
      { value: 'Blade', label: 'Blade'},
      { value: 'Blastaar', label: 'Blastaar'},
      { value: 'Blazing Skull', label: 'Blazing Skull'},
      { value: 'Blindfold', label: 'Blindfold'},
      { value: 'Blink', label: 'Blink'},
      { value: 'Blizzard', label: 'Blizzard'},
      { value: 'Blob', label: 'Blob'},
      { value: 'Blockbuster', label: 'Blockbuster'},
      { value: 'Blok', label: 'Blok'},
      { value: 'Bloke', label: 'Bloke'},
      { value: 'Blonde Phantom', label: 'Blonde Phantom'},
      { value: 'Bloodaxe', label: 'Bloodaxe'},
      { value: 'Bloodscream', label: 'Bloodscream'},
      { value: 'Bloodstorm', label: 'Bloodstorm'},
      { value: 'Bloodstrike', label: 'Bloodstrike'},
      { value: 'Blue Blade', label: 'Blue Blade'},
      { value: 'Blue Marvel', label: 'Blue Marvel'},
      { value: 'Blue Shield', label: 'Blue Shield'},
      { value: 'Blur', label: 'Blur'},
      { value: 'Bob, Agent of Hydra', label: 'Bob, Agent of Hydra'},
      { value: 'Boom Boom', label: 'Boom Boom'},
      { value: 'Boomer', label: 'Boomer'},
      { value: 'Boomerang', label: 'Boomerang'},
      { value: 'Box', label: 'Box'},
      { value: 'Bride of Nine Spiders', label: 'Bride of Nine Spiders'},
      { value: 'Bromley', label: 'Bromley'},
      { value: 'Brood', label: 'Brood'},
      { value: 'Brother Voodoo', label: 'Brother Voodoo'},
      { value: 'Brotherhood of Evil Mutants', label: 'Brotherhood of Evil Mutants'},
      { value: 'Brotherhood of Mutants', label: 'Brotherhood of Mutants'},
      { value: 'Bruce Banner', label: 'Bruce Banner'},
      { value: 'Brute', label: 'Brute'},
      { value: 'Bucky', label: 'Bucky'},
      { value: 'Bug', label: 'Bug'},
      { value: 'Bulldozer', label: 'Bulldozer'},
      { value: 'Bullseye', label: 'Bullseye'},
      { value: 'Bushwacker', label: 'Bushwacker'},
      { value: 'Butterfly', label: 'Butterfly'},
      { value: 'Cable', label: 'Cable'},
      { value: 'Calamity', label: 'Calamity'},
      { value: 'Caliban', label: 'Caliban'},
      { value: 'Callisto', label: 'Callisto'},
      { value: 'Calypso', label: 'Calypso'},
      { value: 'Cammi', label: 'Cammi'},
      { value: 'Cannonball', label: 'Cannonball'},
      { value: 'Cap\'n Oz', label: 'Cap\'n Oz'},
      { value: 'Captain America', label: 'Captain America'},
      { value: 'Captain America/Steve Rogers', label: 'Captain America/Steve Rogers'},
      { value: 'Captain Britain', label: 'Captain Britain'},
      { value: 'Captain Cross', label: 'Captain Cross'},
      { value: 'Captain Flint', label: 'Captain Flint'},
      { value: 'Captain Marvel', label: 'Captain Marvel'},
      { value: 'Captain Midlands', label: 'Captain Midlands'},
      { value: 'Captain Stacy', label: 'Captain Stacy'},
      { value: 'Captain Universe', label: 'Captain Universe'},
      { value: 'Cardiac', label: 'Cardiac'},
      { value: 'Caretaker', label: 'Caretaker'},
      { value: 'Cargill', label: 'Cargill'},
      { value: 'Carlie Cooper', label: 'Carlie Cooper'},
      { value: 'Carmella Unuscione', label: 'Carmella Unuscione'},
      { value: 'Carnage', label: 'Carnage'},
      { value: 'Carol Danvers', label: 'Carol Danvers'},
      { value: 'Carol Hines', label: 'Carol Hines'},
      { value: 'Cassandra Nova', label: 'Cassandra Nova'},
      { value: 'Catseye', label: 'Catseye'},
      { value: 'Cecilia Reyes', label: 'Cecilia Reyes'},
      { value: 'Celestials', label: 'Celestials'},
      { value: 'Centennial', label: 'Centennial'},
      { value: 'Centurions', label: 'Centurions'},
      { value: 'Cerebro', label: 'Cerebro'},
      { value: 'Cerise', label: 'Cerise'},
      { value: 'Ch\'od', label: 'Ch\'od'},
      { value: 'Chamber', label: 'Chamber'},
      { value: 'Chameleon', label: 'Chameleon'},
      { value: 'Champions', label: 'Champions'},
      { value: 'Changeling', label: 'Changeling'},
      { value: 'Charles Xavier', label: 'Charles Xavier'},
      { value: 'Charlie Campion', label: 'Charlie Campion'},
      { value: 'Chase Stein', label: 'Chase Stein'},
      { value: 'Chat', label: 'Chat'},
      { value: 'Chimera', label: 'Chimera'},
      { value: 'Chores MacGillicudy', label: 'Chores MacGillicudy'},
      { value: 'Christian Walker', label: 'Christian Walker'},
      { value: 'Chronomancer', label: 'Chronomancer'},
      { value: 'ClanDestine', label: 'ClanDestine'},
      { value: 'Clea', label: 'Clea'},
      { value: 'Clint Barton', label: 'Clint Barton'},
      { value: 'Cloak', label: 'Cloak'},
      { value: 'Cloud 9', label: 'Cloud 9'},
      { value: 'Cobalt Man', label: 'Cobalt Man'},
      { value: 'Colleen Wing', label: 'Colleen Wing'},
      { value: 'Colonel America', label: 'Colonel America'},
      { value: 'Colossus', label: 'Colossus'},
      { value: 'Confederates of the Curious', label: 'Confederates of the Curious'},
      { value: 'Constrictor', label: 'Constrictor'},
      { value: 'Contessa', label: 'Contessa'},
      { value: 'Controller', label: 'Controller'},
      { value: 'Cornelius', label: 'Cornelius'},
      { value: 'Corsair', label: 'Corsair'},
      { value: 'Cosmo', label: 'Cosmo'},
      { value: 'Cottonmouth', label: 'Cottonmouth'},
      { value: 'Count Nefaria', label: 'Count Nefaria'},
      { value: 'Countess', label: 'Countess'},
      { value: 'Crimson Crusader', label: 'Crimson Crusader'},
      { value: 'Crimson Dynamo', label: 'Crimson Dynamo'},
      { value: 'Crimson King', label: 'Crimson King'},
      { value: 'Crossbones', label: 'Crossbones'},
      { value: 'Crule', label: 'Crule'},
      { value: 'Crusher Hogan', label: 'Crusher Hogan'},
      { value: 'Crystal', label: 'Crystal'},
      { value: 'Cuckoo', label: 'Cuckoo'},
      { value: 'Curt Conners', label: 'Curt Conners'},
      { value: 'Cuthbert', label: 'Cuthbert'},
      { value: 'Cyber', label: 'Cyber'},
      { value: 'Cyclops', label: 'Cyclops'},
      { value: 'Cypher', label: 'Cypher'},
      { value: 'D\'Ken Neramani', label: 'D\'Ken Neramani'},
      { value: 'Dagger', label: 'Dagger'},
      { value: 'Daily Bugle', label: 'Daily Bugle'},
      { value: 'Daimon Hellstrom', label: 'Daimon Hellstrom'},
      { value: 'Daken', label: 'Daken'},
      { value: 'Dakota North', label: 'Dakota North'},
      { value: 'Damage Control', label: 'Damage Control'},
      { value: 'Dani Moonstar', label: 'Dani Moonstar'},
      { value: 'Danny Rand', label: 'Danny Rand'},
      { value: 'Daredevil', label: 'Daredevil'},
      { value: 'Dargo Ktor', label: 'Dargo Ktor'},
      { value: 'Dark Avengers', label: 'Dark Avengers'},
      { value: 'Dark Beast', label: 'Dark Beast'},
      { value: 'Dark Phoenix', label: 'Dark Phoenix'},
      { value: 'Dark X-Men', label: 'Dark X-Men'},
      { value: 'Darkhawk', label: 'Darkhawk'},
      { value: 'Darkstar', label: 'Darkstar'},
      { value: 'Darwin', label: 'Darwin'},
      { value: 'Dazzler', label: 'Dazzler'},
      { value: 'Deacon Frost', label: 'Deacon Frost'},
      { value: 'Dead Girl', label: 'Dead Girl'},
      { value: 'Deadpool', label: 'Deadpool'},
      { value: 'Death', label: 'Death'},
      { value: 'Deathbird', label: 'Deathbird'},
      { value: 'Deathcry', label: 'Deathcry'},
      { value: 'Deathlok', label: 'Deathlok'},
      { value: 'Deathstrike', label: 'Deathstrike'},
      { value: 'Debra Whitman', label: 'Debra Whitman'},
      { value: 'Debrii', label: 'Debrii'},
      { value: 'Deena Pilgrim', label: 'Deena Pilgrim'},
      { value: 'Defenders', label: 'Defenders'},
      { value: 'Demogoblin', label: 'Demogoblin'},
      { value: 'Destiny', label: 'Destiny'},
      { value: 'Detective Soap', label: 'Detective Soap'},
      { value: 'Deviants', label: 'Deviants'},
      { value: 'Devil Dinosaur', label: 'Devil Dinosaur'},
      { value: 'Devos', label: 'Devos'},
      { value: 'Dexter Bennett', label: 'Dexter Bennett'},
      { value: 'Diablo', label: 'Diablo'},
      { value: 'Diamondback', label: 'Diamondback'},
      { value: 'Dinah Soar', label: 'Dinah Soar'},
      { value: 'Dirk Anger', label: 'Dirk Anger'},
      { value: 'Doc Samson', label: 'Doc Samson'},
      { value: 'Doctor Doom', label: 'Doctor Doom'},
      { value: 'Doctor Faustus', label: 'Doctor Faustus'},
      { value: 'Doctor Octopus', label: 'Doctor Octopus'},
      { value: 'Doctor Spectrum', label: 'Doctor Spectrum'},
      { value: 'Doctor Strange', label: 'Doctor Strange'},
      { value: 'Dog Brother #1', label: 'Dog Brother #1'},
      { value: 'Domino', label: 'Domino'},
      { value: 'Donald Blake', label: 'Donald Blake'},
      { value: 'Doomsday Man', label: 'Doomsday Man'},
      { value: 'Doop', label: 'Doop'},
      { value: 'Doorman', label: 'Doorman'},
      { value: 'Dorian Gray', label: 'Dorian Gray'},
      { value: 'Dormammu', label: 'Dormammu'},
      { value: 'Dr. Strange', label: 'Dr. Strange'},
      { value: 'Dracula', label: 'Dracula'},
      { value: 'Dragon Lord', label: 'Dragon Lord'},
      { value: 'Dragon Man', label: 'Dragon Man'},
      { value: 'Drax', label: 'Drax'},
      { value: 'Dreadnoughts', label: 'Dreadnoughts'},
      { value: 'Dreaming Celestial', label: 'Dreaming Celestial'},
      { value: 'Druig', label: 'Druig'},
      { value: 'Dum Dum Dugan', label: 'Dum Dum Dugan'},
      { value: 'Dust', label: 'Dust'},
      { value: 'Earthquake', label: 'Earthquake'},
      { value: 'Echo', label: 'Echo'},
      { value: 'Eddie Brock', label: 'Eddie Brock'},
      { value: 'Eddie Lau', label: 'Eddie Lau'},
      { value: 'Edward \"Ted\" Forrester', label: 'Edward \"Ted\" Forrester'},
      { value: 'Edwin Jarvis', label: 'Edwin Jarvis'},
      { value: 'Ego', label: 'Ego'},
      { value: 'Electro', label: 'Electro'},
      { value: 'Elektra', label: 'Elektra'},
      { value: 'Elements of Doom', label: 'Elements of Doom'},
      { value: 'Elite', label: 'Elite'},
      { value: 'Elixir', label: 'Elixir'},
      { value: 'Elloe Kaifi', label: 'Elloe Kaifi'},
      { value: 'Elsa Bloodstone', label: 'Elsa Bloodstone'},
      { value: 'Emma Frost', label: 'Emma Frost'},
      { value: 'Empath', label: 'Empath'},
      { value: 'Emplate', label: 'Emplate'},
      { value: 'Enchantress', label: 'Enchantress'},
      { value: 'Ender Wiggin', label: 'Ender Wiggin'},
      { value: 'Energizer', label: 'Energizer'},
      { value: 'Epoch', label: 'Epoch'},
      { value: 'Erik the Red', label: 'Erik the Red'},
      { value: 'Eternals', label: 'Eternals'},
      { value: 'Eternity', label: 'Eternity'},
      { value: 'Excalibur', label: 'Excalibur'},
      { value: 'Exiles', label: 'Exiles'},
      { value: 'Exodus', label: 'Exodus'},
      { value: 'Expediter', label: 'Expediter'},
      { value: 'Ezekiel', label: 'Ezekiel'},
      { value: 'Ezekiel Stane', label: 'Ezekiel Stane'},
      { value: 'Fabian Cortez', label: 'Fabian Cortez'},
      { value: 'Falcon', label: 'Falcon'},
      { value: 'Falcon/Sam Wilson', label: 'Falcon/Sam Wilson'},
      { value: 'Fallen One', label: 'Fallen One'},
      { value: 'Famine', label: 'Famine'},
      { value: 'Fantastic Four', label: 'Fantastic Four'},
      { value: 'Fantastick Four', label: 'Fantastick Four'},
      { value: 'Fantomex', label: 'Fantomex'},
      { value: 'Fat Cobra', label: 'Fat Cobra'},
      { value: 'Felicia Hardy', label: 'Felicia Hardy'},
      { value: 'Fenris', label: 'Fenris'},
      { value: 'Feral', label: 'Feral'},
      { value: 'Fin Fang Foom', label: 'Fin Fang Foom'},
      { value: 'Firebird', label: 'Firebird'},
      { value: 'Firebrand', label: 'Firebrand'},
      { value: 'Firedrake', label: 'Firedrake'},
      { value: 'Firelord', label: 'Firelord'},
      { value: 'Firestar', label: 'Firestar'},
      { value: 'Fixer', label: 'Fixer'},
      { value: 'Flatman', label: 'Flatman'},
      { value: 'Flying Dutchman', label: 'Flying Dutchman'},
      { value: 'Foggy Nelson', label: 'Foggy Nelson'},
      { value: 'Force Works', label: 'Force Works'},
      { value: 'Forearm', label: 'Forearm'},
      { value: 'Forge', label: 'Forge'},
      { value: 'Forgotten One', label: 'Forgotten One'},
      { value: 'Frank Castle', label: 'Frank Castle'},
      { value: 'Frankenstein\'s Monster', label: 'Frankenstein\'s Monster'},
      { value: 'Franklin Richards', label: 'Franklin Richards'},
      { value: 'Franklin Storm', label: 'Franklin Storm'},
      { value: 'Freak', label: 'Freak'},
      { value: 'Frightful Four', label: 'Frightful Four'},
      { value: 'Frog Thor', label: 'Frog Thor'},
      { value: 'Frog-Man', label: 'Frog-Man'},
      { value: 'Gabe Jones', label: 'Gabe Jones'},
      { value: 'Galactus', label: 'Galactus'},
      { value: 'Galia', label: 'Galia'},
      { value: 'Gambit', label: 'Gambit'},
      { value: 'Gamma Corps', label: 'Gamma Corps'},
      { value: 'Gamora', label: 'Gamora'},
      { value: 'Gargoyle', label: 'Gargoyle'},
      { value: 'Garia', label: 'Garia'},
      { value: 'Garrison Kane', label: 'Garrison Kane'},
      { value: 'Gateway', label: 'Gateway'},
      { value: 'Gauntlet', label: 'Gauntlet'},
      { value: 'Geiger', label: 'Geiger'},
      { value: 'Gene Sailors', label: 'Gene Sailors'},
      { value: 'Generation X', label: 'Generation X'},
      { value: 'Genesis', label: 'Genesis'},
      { value: 'Genis-Vell', label: 'Genis-Vell'},
      { value: 'George Stacy', label: 'George Stacy'},
      { value: 'Gertrude Yorkes', label: 'Gertrude Yorkes'},
      { value: 'Ghost Rider', label: 'Ghost Rider'},
      { value: 'Giant Girl', label: 'Giant Girl'},
      { value: 'Giant Man', label: 'Giant Man'},
      { value: 'Giant-dok', label: 'Giant-dok'},
      { value: 'Giant-Man', label: 'Giant-Man'},
      { value: 'Gideon', label: 'Gideon'},
      { value: 'Git Hoskins', label: 'Git Hoskins'},
      { value: 'Gladiator', label: 'Gladiator'},
      { value: 'Glenn Talbot', label: 'Glenn Talbot'},
      { value: 'Glorian', label: 'Glorian'},
      { value: 'Goblin Queen', label: 'Goblin Queen'},
      { value: 'Golden Guardian', label: 'Golden Guardian'},
      { value: 'Goliath', label: 'Goliath'},
      { value: 'Gorgon', label: 'Gorgon'},
      { value: 'Gorilla Man', label: 'Gorilla Man'},
      { value: 'Grandmaster', label: 'Grandmaster'},
      { value: 'Gravity', label: 'Gravity'},
      { value: 'Great Lakes Avengers', label: 'Great Lakes Avengers'},
      { value: 'Green Goblin', label: 'Green Goblin'},
      { value: 'Gressill', label: 'Gressill'},
      { value: 'Grey Gargoyle', label: 'Grey Gargoyle'},
      { value: 'Greymalkin', label: 'Greymalkin'},
      { value: 'Grim Reaper', label: 'Grim Reaper'},
      { value: 'Groot', label: 'Groot'},
      { value: 'Guardian', label: 'Guardian'},
      { value: 'Guardians of the Galaxy', label: 'Guardians of the Galaxy'},
      { value: 'Guardsmen', label: 'Guardsmen'},
      { value: 'Gunslinger', label: 'Gunslinger'},
      { value: 'GW Bridge', label: 'GW Bridge'},
      { value: 'Gwen Stacy', label: 'Gwen Stacy'},
      { value: 'H.A.M.M.E.R.', label: 'H.A.M.M.E.R.'},
      { value: 'H.E.R.B.I.E.', label: 'H.E.R.B.I.E.'},
      { value: 'Hairball', label: 'Hairball'},
      { value: 'Half-Life', label: 'Half-Life'},
      { value: 'Hammerhead', label: 'Hammerhead'},
      { value: 'Hank Pym', label: 'Hank Pym'},
      { value: 'Hannibal King', label: 'Hannibal King'},
      { value: 'Happy Hogan', label: 'Happy Hogan'},
      { value: 'Hardball', label: 'Hardball'},
      { value: 'Harley Davidson Cooper', label: 'Harley Davidson Cooper'},
      { value: 'Harpoon', label: 'Harpoon'},
      { value: 'Harrier', label: 'Harrier'},
      { value: 'Harry Heck', label: 'Harry Heck'},
      { value: 'Harry Osborn', label: 'Harry Osborn'},
      { value: 'Hate-Monger', label: 'Hate-Monger'},
      { value: 'Havok', label: 'Havok'},
      { value: 'Hawkeye', label: 'Hawkeye'},
      { value: 'Hawkeye/Clint Barton', label: 'Hawkeye/Clint Barton'},
      { value: 'Hedge Knight', label: 'Hedge Knight'},
      { value: 'Hellcat', label: 'Hellcat'},
      { value: 'Hellfire Club', label: 'Hellfire Club'},
      { value: 'Hellion', label: 'Hellion'},
      { value: 'Hellions', label: 'Hellions'},
      { value: 'Hemingway', label: 'Hemingway'},
      { value: 'Henry Peter Gyrich', label: 'Henry Peter Gyrich'},
      { value: 'Hepzibah', label: 'Hepzibah'},
      { value: 'Hercules', label: 'Hercules'},
      { value: 'Heroes For Hire', label: 'Heroes For Hire'},
      { value: 'Hex', label: 'Hex'},
      { value: 'High Evolutionary', label: 'High Evolutionary'},
      { value: 'Hindsight Lad', label: 'Hindsight Lad'},
      { value: 'Hiroim', label: 'Hiroim'},
      { value: 'Hitman', label: 'Hitman'},
      { value: 'Hitomi Sakuma', label: 'Hitomi Sakuma'},
      { value: 'Hobgoblin', label: 'Hobgoblin'},
      { value: 'Holocaust', label: 'Holocaust'},
      { value: 'Holy', label: 'Holy'},
      { value: 'Hope Summers', label: 'Hope Summers'},
      { value: 'Howard Saint', label: 'Howard Saint'},
      { value: 'Howard The Duck', label: 'Howard The Duck'},
      { value: 'Hulk', label: 'Hulk'},
      { value: 'Hulk-dok', label: 'Hulk-dok'},
      { value: 'Hulk/Bruce Banner', label: 'Hulk/Bruce Banner'},
      { value: 'Hulkling', label: 'Hulkling'},
      { value: 'Human Cannonball', label: 'Human Cannonball'},
      { value: 'Human Fly', label: 'Human Fly'},
      { value: 'Human Robot', label: 'Human Robot'},
      { value: 'Human Torch', label: 'Human Torch'},
      { value: 'Humbug', label: 'Humbug'},
      { value: 'Husk', label: 'Husk'},
      { value: 'Hussar', label: 'Hussar'},
      { value: 'Hydra', label: 'Hydra'},
      { value: 'Hydro-Man', label: 'Hydro-Man'},
      { value: 'Hyperion', label: 'Hyperion'},
      { value: 'Hypno-Hustler', label: 'Hypno-Hustler'},
      { value: 'Iceman', label: 'Iceman'},
      { value: 'Ikaris', label: 'Ikaris'},
      { value: 'Illuminati', label: 'Illuminati'},
      { value: 'Ilyana Rasputin', label: 'Ilyana Rasputin'},
      { value: 'Imp', label: 'Imp'},
      { value: 'Imperfects', label: 'Imperfects'},
      { value: 'Imperial Guard', label: 'Imperial Guard'},
      { value: 'Impossible Man', label: 'Impossible Man'},
      { value: 'In-Betweener', label: 'In-Betweener'},
      { value: 'Inertia', label: 'Inertia'},
      { value: 'Infant Terrible', label: 'Infant Terrible'},
      { value: 'Inhumans', label: 'Inhumans'},
      { value: 'Ink', label: 'Ink'},
      { value: 'Invaders', label: 'Invaders'},
      { value: 'Invisible Woman', label: 'Invisible Woman'},
      { value: 'Iron Cross Army', label: 'Iron Cross Army'},
      { value: 'Iron Fist', label: 'Iron Fist'},
      { value: 'Iron Lad', label: 'Iron Lad'},
      { value: 'Iron Man', label: 'Iron Man'},
      { value: 'Iron Man/Tony Stark', label: 'Iron Man/Tony Stark'},
      { value: 'Iron Monger', label: 'Iron Monger'},
      { value: 'Iron Patriot', label: 'Iron Patriot'},
      { value: 'Ironclad', label: 'Ironclad'},
      { value: 'J. Jonah Jameson', label: 'J. Jonah Jameson'},
      { value: 'Jack Flag', label: 'Jack Flag'},
      { value: 'Jack Murdock', label: 'Jack Murdock'},
      { value: 'Jack O\' Lantern', label: 'Jack O\' Lantern'},
      { value: 'Jack Power', label: 'Jack Power'},
      { value: 'Jackal', label: 'Jackal'},
      { value: 'Jackpot', label: 'Jackpot'},
      { value: 'James Buchanan Barnes', label: 'James Buchanan Barnes'},
      { value: 'James Howlett', label: 'James Howlett'},
      { value: 'Jamie Braddock', label: 'Jamie Braddock'},
      { value: 'Jane Foster', label: 'Jane Foster'},
      { value: 'Janus, the Nega-Man', label: 'Janus, the Nega-Man'},
      { value: 'Jasper Sitwell', label: 'Jasper Sitwell'},
      { value: 'Jazinda', label: 'Jazinda'},
      { value: 'Jean Grey', label: 'Jean Grey'},
      { value: 'Jennifer Smith', label: 'Jennifer Smith'},
      { value: 'Jeryn Hogarth', label: 'Jeryn Hogarth'},
      { value: 'Jessica Drew', label: 'Jessica Drew'},
      { value: 'Jessica Jones', label: 'Jessica Jones'},
      { value: 'Jetstream', label: 'Jetstream'},
      { value: 'Jigsaw', label: 'Jigsaw'},
      { value: 'Jimmy Woo', label: 'Jimmy Woo'},
      { value: 'Joan the Mouse', label: 'Joan the Mouse'},
      { value: 'Jocasta', label: 'Jocasta'},
      { value: 'John Farson', label: 'John Farson'},
      { value: 'John Jameson', label: 'John Jameson'},
      { value: 'John Porter', label: 'John Porter'},
      { value: 'John Wraith', label: 'John Wraith'},
      { value: 'Johnny Blaze', label: 'Johnny Blaze'},
      { value: 'Johnny Storm', label: 'Johnny Storm'},
      { value: 'Joseph', label: 'Joseph'},
      { value: 'Joshua Kane', label: 'Joshua Kane'},
      { value: 'Josiah X', label: 'Josiah X'},
      { value: 'Joystick', label: 'Joystick'},
      { value: 'Jubilee', label: 'Jubilee'},
      { value: 'Juggernaut', label: 'Juggernaut'},
      { value: 'Jule Carpenter', label: 'Jule Carpenter'},
      { value: 'Julian Keller', label: 'Julian Keller'},
      { value: 'Junta', label: 'Junta'},
      { value: 'Justice', label: 'Justice'},
      { value: 'Justin Hammer', label: 'Justin Hammer'},
      { value: 'Ka-Zar', label: 'Ka-Zar'},
      { value: 'Kabuki', label: 'Kabuki'},
      { value: 'Kang', label: 'Kang'},
      { value: 'Karen O\'Malley', label: 'Karen O\'Malley'},
      { value: 'Karen Page', label: 'Karen Page'},
      { value: 'Karma', label: 'Karma'},
      { value: 'Karnak', label: 'Karnak'},
      { value: 'Karolina Dean ', label: 'Karolina Dean '},
      { value: 'Kat Farrell', label: 'Kat Farrell'},
      { value: 'Kate Bishop', label: 'Kate Bishop'},
      { value: 'Katie Power', label: 'Katie Power'},
      { value: 'Ken Ellis', label: 'Ken Ellis'},
      { value: 'Khan', label: 'Khan'},
      { value: 'Kid Colt', label: 'Kid Colt'},
      { value: 'Killer Shrike', label: 'Killer Shrike'},
      { value: 'Killmonger', label: 'Killmonger'},
      { value: 'Killraven', label: 'Killraven'},
      { value: 'King Bedlam', label: 'King Bedlam'},
      { value: 'King Cobra', label: 'King Cobra'},
      { value: 'Kingpin', label: 'Kingpin'},
      { value: 'Kinsey Walden', label: 'Kinsey Walden'},
      { value: 'Kitty Pryde', label: 'Kitty Pryde'},
      { value: 'Klaw', label: 'Klaw'},
      { value: 'Komodo', label: 'Komodo'},
      { value: 'Korath', label: 'Korath'},
      { value: 'Korg', label: 'Korg'},
      { value: 'Korvac', label: 'Korvac'},
      { value: 'Kraven the Hunter', label: 'Kraven the Hunter'},
      { value: 'Kree', label: 'Kree'},
      { value: 'Krista Starr', label: 'Krista Starr'},
      { value: 'Kronos', label: 'Kronos'},
      { value: 'Kulan Gath', label: 'Kulan Gath'},
      { value: 'Kylun', label: 'Kylun'},
      { value: 'La Nuit', label: 'La Nuit'},
      { value: 'Lady Bullseye', label: 'Lady Bullseye'},
      { value: 'Lady Deathstrike', label: 'Lady Deathstrike'},
      { value: 'Lady Mastermind', label: 'Lady Mastermind'},
      { value: 'Lady Ursula', label: 'Lady Ursula'},
      { value: 'Lady Vermin', label: 'Lady Vermin'},
      { value: 'Lake', label: 'Lake'},
      { value: 'Landau', label: 'Landau'},
      { value: 'Lava-Man', label: 'Lava-Man'},
      { value: 'Layla Miller', label: 'Layla Miller'},
      { value: 'Leader', label: 'Leader'},
      { value: 'Leech', label: 'Leech'},
      { value: 'Legion', label: 'Legion'},
      { value: 'Lei Kung, The Thunderer', label: 'Lei Kung, The Thunderer'},
      { value: 'Lenny Balinger', label: 'Lenny Balinger'},
      { value: 'Leo', label: 'Leo'},
      { value: 'Leopardon', label: 'Leopardon'},
      { value: 'Leper Queen', label: 'Leper Queen'},
      { value: 'Lester', label: 'Lester'},
      { value: 'Lethal Legion', label: 'Lethal Legion'},
      { value: 'Lieutenant Marcus Stone', label: 'Lieutenant Marcus Stone'},
      { value: 'Lifeguard', label: 'Lifeguard'},
      { value: 'Lightning Lords of Nepal', label: 'Lightning Lords of Nepal'},
      { value: 'Lightspeed', label: 'Lightspeed'},
      { value: 'Lila Cheney', label: 'Lila Cheney'},
      { value: 'Lilandra', label: 'Lilandra'},
      { value: 'Lilith', label: 'Lilith'},
      { value: 'Lily Hollister', label: 'Lily Hollister'},
      { value: 'Lionheart', label: 'Lionheart'},
      { value: 'Living Lightning', label: 'Living Lightning'},
      { value: 'Living Mummy', label: 'Living Mummy'},
      { value: 'Living Tribunal', label: 'Living Tribunal'},
      { value: 'Liz Osborn', label: 'Liz Osborn'},
      { value: 'Lizard', label: 'Lizard'},
      { value: 'Loa', label: 'Loa'},
      { value: 'Lockheed', label: 'Lockheed'},
      { value: 'Lockjaw', label: 'Lockjaw'},
      { value: 'Logan', label: 'Logan'},
      { value: 'Loki', label: 'Loki'},
      { value: 'Loners', label: 'Loners'},
      { value: 'Longshot', label: 'Longshot'},
      { value: 'Lord Hawal', label: 'Lord Hawal'},
      { value: 'Lord Tyger', label: 'Lord Tyger'},
      { value: 'Lords of Avalon', label: 'Lords of Avalon'},
      { value: 'Lorna Dane', label: 'Lorna Dane'},
      { value: 'Luckman', label: 'Luckman'},
      { value: 'Lucky Pierre', label: 'Lucky Pierre'},
      { value: 'Lucy in the Sky', label: 'Lucy in the Sky'},
      { value: 'Luke Cage', label: 'Luke Cage'},
      { value: 'Luminals', label: 'Luminals'},
      { value: 'Lyja', label: 'Lyja'},
      { value: 'M', label: 'M'},
      { value: 'M.O.D.A.M.', label: 'M.O.D.A.M.'},
      { value: 'M.O.D.O.G.', label: 'M.O.D.O.G.'},
      { value: 'M.O.D.O.K.', label: 'M.O.D.O.K.'},
      { value: 'Ma Gnuci', label: 'Ma Gnuci'},
      { value: 'Mac Gargan', label: 'Mac Gargan'},
      { value: 'Mach IV', label: 'Mach IV'},
      { value: 'Machine Man', label: 'Machine Man'},
      { value: 'Mad Thinker', label: 'Mad Thinker'},
      { value: 'Madame Hydra', label: 'Madame Hydra'},
      { value: 'Madame Masque', label: 'Madame Masque'},
      { value: 'Madame Web', label: 'Madame Web'},
      { value: 'Maddog', label: 'Maddog'},
      { value: 'Madelyne Pryor', label: 'Madelyne Pryor'},
      { value: 'Madripoor', label: 'Madripoor'},
      { value: 'Madrox', label: 'Madrox'},
      { value: 'Maelstrom', label: 'Maelstrom'},
      { value: 'Maestro', label: 'Maestro'},
      { value: 'Magdalene', label: 'Magdalene'},
      { value: 'Maggott', label: 'Maggott'},
      { value: 'Magik', label: 'Magik'},
      { value: 'Maginty', label: 'Maginty'},
      { value: 'Magma', label: 'Magma'},
      { value: 'Magneto', label: 'Magneto'},
      { value: 'Magus', label: 'Magus'},
      { value: 'Major Mapleleaf', label: 'Major Mapleleaf'},
      { value: 'Makkari', label: 'Makkari'},
      { value: 'Malcolm Colcord', label: 'Malcolm Colcord'},
      { value: 'Malice', label: 'Malice'},
      { value: 'Man-Thing', label: 'Man-Thing'},
      { value: 'Man-Wolf', label: 'Man-Wolf'},
      { value: 'Mandarin', label: 'Mandarin'},
      { value: 'Mandrill', label: 'Mandrill'},
      { value: 'Mandroid', label: 'Mandroid'},
      { value: 'Manta', label: 'Manta'},
      { value: 'Mantis', label: 'Mantis'},
      { value: 'Marauders', label: 'Marauders'},
      { value: 'Marcus Van Sciver', label: 'Marcus Van Sciver'},
      { value: 'Maria Hill', label: 'Maria Hill'},
      { value: 'Mariko Yashida', label: 'Mariko Yashida'},
      { value: 'Marrow', label: 'Marrow'},
      { value: 'Marten Broadcloak', label: 'Marten Broadcloak'},
      { value: 'Martin Li', label: 'Martin Li'},
      { value: 'Marvel Apes', label: 'Marvel Apes'},
      { value: 'Marvel Boy', label: 'Marvel Boy'},
      { value: 'Marvel Zombies', label: 'Marvel Zombies'},
      { value: 'Marvex', label: 'Marvex'},
      { value: 'Mary Jane Watson', label: 'Mary Jane Watson'},
      { value: 'Masked Marvel', label: 'Masked Marvel'},
      { value: 'Masque', label: 'Masque'},
      { value: 'Master Chief', label: 'Master Chief'},
      { value: 'Master Mold', label: 'Master Mold'},
      { value: 'Mastermind', label: 'Mastermind'},
      { value: 'Masters of Evil', label: 'Masters of Evil'},
      { value: 'Mathemanic', label: 'Mathemanic'},
      { value: 'Matsu\'o Tsurayaba', label: 'Matsu\'o Tsurayaba'},
      { value: 'Matthew Murdock', label: 'Matthew Murdock'},
      { value: 'Mattie Franklin', label: 'Mattie Franklin'},
      { value: 'Mauler', label: 'Mauler'},
      { value: 'Maverick', label: 'Maverick'},
      { value: 'Maximus', label: 'Maximus'},
      { value: 'May Parker', label: 'May Parker'},
      { value: 'Medusa', label: 'Medusa'},
      { value: 'Meggan', label: 'Meggan'},
      { value: 'Meltdown', label: 'Meltdown'},
      { value: 'Menace', label: 'Menace'},
      { value: 'Mentallo', label: 'Mentallo'},
      { value: 'Mentor', label: 'Mentor'},
      { value: 'Mephisto', label: 'Mephisto'},
      { value: 'Mephistopheles', label: 'Mephistopheles'},
      { value: 'Mercury', label: 'Mercury'},
      { value: 'Mesmero', label: 'Mesmero'},
      { value: 'Metal Master', label: 'Metal Master'},
      { value: 'Meteorite', label: 'Meteorite'},
      { value: 'MI: 13', label: 'MI: 13'},
      { value: 'Micro/Macro', label: 'Micro/Macro'},
      { value: 'Microbe', label: 'Microbe'},
      { value: 'Microchip', label: 'Microchip'},
      { value: 'Micromax', label: 'Micromax'},
      { value: 'Midnight', label: 'Midnight'},
      { value: 'Miek', label: 'Miek'},
      { value: 'Mikhail Rasputin', label: 'Mikhail Rasputin'},
      { value: 'Millenium Guard', label: 'Millenium Guard'},
      { value: 'Millie the Model', label: 'Millie the Model'},
      { value: 'Mimic', label: 'Mimic'},
      { value: 'Mindworm', label: 'Mindworm'},
      { value: 'Miracleman', label: 'Miracleman'},
      { value: 'Miss America', label: 'Miss America'},
      { value: 'Mister Fear', label: 'Mister Fear'},
      { value: 'Mister Sinister', label: 'Mister Sinister'},
      { value: 'Misty Knight', label: 'Misty Knight'},
      { value: 'Mockingbird', label: 'Mockingbird'},
      { value: 'Moira MacTaggert', label: 'Moira MacTaggert'},
      { value: 'Mojo', label: 'Mojo'},
      { value: 'Mole Man', label: 'Mole Man'},
      { value: 'Molecule Man', label: 'Molecule Man'},
      { value: 'Molly Hayes', label: 'Molly Hayes'},
      { value: 'Molly Von Richtofen', label: 'Molly Von Richtofen'},
      { value: 'Molten Man', label: 'Molten Man'},
      { value: 'Mongoose', label: 'Mongoose'},
      { value: 'Mongu', label: 'Mongu'},
      { value: 'Monster Badoon', label: 'Monster Badoon'},
      { value: 'Moon Knight', label: 'Moon Knight'},
      { value: 'Moondragon', label: 'Moondragon'},
      { value: 'Moonstone', label: 'Moonstone'},
      { value: 'Morbius', label: 'Morbius'},
      { value: 'Mordo', label: 'Mordo'},
      { value: 'Morg', label: 'Morg'},
      { value: 'Morgan Stark', label: 'Morgan Stark'},
      { value: 'Morlocks', label: 'Morlocks'},
      { value: 'Morlun', label: 'Morlun'},
      { value: 'Morph', label: 'Morph'},
      { value: 'Mother Askani', label: 'Mother Askani'},
      { value: 'Mr. Bumpo', label: 'Mr. Bumpo'},
      { value: 'Mr. Fantastic', label: 'Mr. Fantastic'},
      { value: 'Mr. Fish', label: 'Mr. Fish'},
      { value: 'Mr. Fixit', label: 'Mr. Fixit'},
      { value: 'Mr. Hyde', label: 'Mr. Hyde'},
      { value: 'Mr. Immortal', label: 'Mr. Immortal'},
      { value: 'Mr. Meugniot', label: 'Mr. Meugniot'},
      { value: 'Mr. Negative', label: 'Mr. Negative'},
      { value: 'Mr. Payback', label: 'Mr. Payback'},
      { value: 'Mr. X', label: 'Mr. X'},
      { value: 'MS2', label: 'MS2'},
      { value: 'Ms. Marvel', label: 'Ms. Marvel'},
      { value: 'Mulholland Black', label: 'Mulholland Black'},
      { value: 'Multiple Man', label: 'Multiple Man'},
      { value: 'MVP', label: 'MVP'},
      { value: 'Mysterio', label: 'Mysterio'},
      { value: 'Mystique', label: 'Mystique'},
      { value: 'Namor', label: 'Namor'},
      { value: 'Namora', label: 'Namora'},
      { value: 'Namorita', label: 'Namorita'},
      { value: 'Naoko', label: 'Naoko'},
      { value: 'Natasha Romanoff', label: 'Natasha Romanoff'},
      { value: 'Nebula', label: 'Nebula'},
      { value: 'Nehzno', label: 'Nehzno'},
      { value: 'Nekra', label: 'Nekra'},
      { value: 'Nemesis', label: 'Nemesis'},
      { value: 'Network', label: 'Network'},
      { value: 'New Goblin', label: 'New Goblin'},
      { value: 'New Mutants', label: 'New Mutants'},
      { value: 'New Warriors', label: 'New Warriors'},
      { value: 'New X-Men', label: 'New X-Men'},
      { value: 'Newton Destine', label: 'Newton Destine'},
      { value: 'Next Avengers', label: 'Next Avengers'},
      { value: 'Nextwave', label: 'Nextwave'},
      { value: 'Nick Fury', label: 'Nick Fury'},
      { value: 'Nico Minoru', label: 'Nico Minoru'},
      { value: 'Nicolaos', label: 'Nicolaos'},
      { value: 'Night Nurse', label: 'Night Nurse'},
      { value: 'Night Thrasher', label: 'Night Thrasher'},
      { value: 'Nightcrawler', label: 'Nightcrawler'},
      { value: 'Nighthawk', label: 'Nighthawk'},
      { value: 'Nightmare', label: 'Nightmare'},
      { value: 'Nightshade', label: 'Nightshade'},
      { value: 'Nine-Fold Daughters of Xao', label: 'Nine-Fold Daughters of Xao'},
      { value: 'Nitro', label: 'Nitro'},
      { value: 'Nocturne', label: 'Nocturne'},
      { value: 'Nomad', label: 'Nomad'},
      { value: 'Norman Osborn', label: 'Norman Osborn'},
      { value: 'Norrin Radd', label: 'Norrin Radd'},
      { value: 'Northstar', label: 'Northstar'},
      { value: 'Nova', label: 'Nova'},
      { value: 'Nuke', label: 'Nuke'},
      { value: 'Obadiah Stane', label: 'Obadiah Stane'},
      { value: 'Odin', label: 'Odin'},
      { value: 'Ogun', label: 'Ogun'},
      { value: 'Old Lace', label: 'Old Lace'},
      { value: 'Omega Flight', label: 'Omega Flight'},
      { value: 'Omega Red', label: 'Omega Red'},
      { value: 'Omega Sentinel', label: 'Omega Sentinel'},
      { value: 'Omega the Unknown', label: 'Omega the Unknown'},
      { value: 'Onslaught', label: 'Onslaught'},
      { value: 'Oracle', label: 'Oracle'},
      { value: 'Ord', label: 'Ord'},
      { value: 'Orphan', label: 'Orphan'},
      { value: 'Orphan-Maker', label: 'Orphan-Maker'},
      { value: 'Otto Octavius', label: 'Otto Octavius'},
      { value: 'Outlaw Kid', label: 'Outlaw Kid'},
      { value: 'Overlord', label: 'Overlord'},
      { value: 'Owl', label: 'Owl'},
      { value: 'Ozymandias', label: 'Ozymandias'},
      { value: 'Paibok', label: 'Paibok'},
      { value: 'Paladin', label: 'Paladin'},
      { value: 'Pandemic', label: 'Pandemic'},
      { value: 'Paper Doll', label: 'Paper Doll'},
      { value: 'Patch', label: 'Patch'},
      { value: 'Patriot', label: 'Patriot'},
      { value: 'Payback', label: 'Payback'},
      { value: 'Penance', label: 'Penance'},
      { value: 'Pepper Potts', label: 'Pepper Potts'},
      { value: 'Pestilence', label: 'Pestilence'},
      { value: 'Pet Avengers', label: 'Pet Avengers'},
      { value: 'Pete Wisdom', label: 'Pete Wisdom'},
      { value: 'Peter Parker', label: 'Peter Parker'},
      { value: 'Peter Quill', label: 'Peter Quill'},
      { value: 'Phalanx', label: 'Phalanx'},
      { value: 'Phantom Reporter', label: 'Phantom Reporter'},
      { value: 'Phil Sheldon', label: 'Phil Sheldon'},
      { value: 'Photon', label: 'Photon'},
      { value: 'Phyla-Vell', label: 'Phyla-Vell'},
      { value: 'Piledriver', label: 'Piledriver'},
      { value: 'Pip', label: 'Pip'},
      { value: 'Pixie', label: 'Pixie'},
      { value: 'Plazm', label: 'Plazm'},
      { value: 'Polaris', label: 'Polaris'},
      { value: 'Post', label: 'Post'},
      { value: 'Power Man', label: 'Power Man'},
      { value: 'Power Pack', label: 'Power Pack'},
      { value: 'Praxagora', label: 'Praxagora'},
      { value: 'Preak', label: 'Preak'},
      { value: 'Pretty Boy', label: 'Pretty Boy'},
      { value: 'Pride', label: 'Pride'},
      { value: 'Prima', label: 'Prima'},
      { value: 'Prince of Orphans', label: 'Prince of Orphans'},
      { value: 'Princess Powerful', label: 'Princess Powerful'},
      { value: 'Prism', label: 'Prism'},
      { value: 'Prodigy', label: 'Prodigy'},
      { value: 'Proemial Gods', label: 'Proemial Gods'},
      { value: 'Professor Monster', label: 'Professor Monster'},
      { value: 'Professor X', label: 'Professor X'},
      { value: 'Proteus', label: 'Proteus'},
      { value: 'Proudstar', label: 'Proudstar'},
      { value: 'Prowler', label: 'Prowler'},
      { value: 'Psycho-Man', label: 'Psycho-Man'},
      { value: 'Psylocke', label: 'Psylocke'},
      { value: 'PsyNapse', label: 'PsyNapse'},
      { value: 'Puck', label: 'Puck'},
      { value: 'Puff Adder', label: 'Puff Adder'},
      { value: 'pug', label: 'pug'},
      { value: 'Puma', label: 'Puma'},
      { value: 'Punisher', label: 'Punisher'},
      { value: 'Puppet Master', label: 'Puppet Master'},
      { value: 'Purifiers', label: 'Purifiers'},
      { value: 'Purple Man', label: 'Purple Man'},
      { value: 'Pyro', label: 'Pyro'},
      { value: 'Quasar', label: 'Quasar'},
      { value: 'Quasimodo', label: 'Quasimodo'},
      { value: 'Queen Noir', label: 'Queen Noir'},
      { value: 'Quentin Quire', label: 'Quentin Quire'},
      { value: 'Quicksilver', label: 'Quicksilver'},
      { value: 'Rachel Grey', label: 'Rachel Grey'},
      { value: 'Radioactive Man', label: 'Radioactive Man'},
      { value: 'Rafael Vega', label: 'Rafael Vega'},
      { value: 'Rage', label: 'Rage'},
      { value: 'Raider', label: 'Raider'},
      { value: 'Randall', label: 'Randall'},
      { value: 'Randall Flagg', label: 'Randall Flagg'},
      { value: 'Random', label: 'Random'},
      { value: 'Rattler', label: 'Rattler'},
      { value: 'Ravenous', label: 'Ravenous'},
      { value: 'Rawhide Kid', label: 'Rawhide Kid'},
      { value: 'Raza', label: 'Raza'},
      { value: 'Reaper', label: 'Reaper'},
      { value: 'Reavers', label: 'Reavers'},
      { value: 'Red 9', label: 'Red 9'},
      { value: 'Red Ghost', label: 'Red Ghost'},
      { value: 'Red Hulk', label: 'Red Hulk'},
      { value: 'Red She-Hulk', label: 'Red She-Hulk'},
      { value: 'Red Shift', label: 'Red Shift'},
      { value: 'Red Skull', label: 'Red Skull'},
      { value: 'Red Wolf', label: 'Red Wolf'},
      { value: 'Redwing', label: 'Redwing'},
      { value: 'Reptil', label: 'Reptil'},
      { value: 'Retro Girl', label: 'Retro Girl'},
      { value: 'Revanche', label: 'Revanche'},
      { value: 'Rhino', label: 'Rhino'},
      { value: 'Rhodey', label: 'Rhodey'},
      { value: 'Richard Fisk', label: 'Richard Fisk'},
      { value: 'Rick Jones', label: 'Rick Jones'},
      { value: 'Ricochet', label: 'Ricochet'},
      { value: 'Rictor', label: 'Rictor'},
      { value: 'Riptide', label: 'Riptide'},
      { value: 'Risque', label: 'Risque'},
      { value: 'Robbie Robertson', label: 'Robbie Robertson'},
      { value: 'Robert Baldwin ', label: 'Robert Baldwin '},
      { value: 'Robin Chapel', label: 'Robin Chapel'},
      { value: 'Rocket Raccoon', label: 'Rocket Raccoon'},
      { value: 'Rocket Racer', label: 'Rocket Racer'},
      { value: 'Rockslide', label: 'Rockslide'},
      { value: 'Rogue', label: 'Rogue'},
      { value: 'Roland Deschain', label: 'Roland Deschain'},
      { value: 'Romulus', label: 'Romulus'},
      { value: 'Ronan', label: 'Ronan'},
      { value: 'Roughhouse', label: 'Roughhouse'},
      { value: 'Roulette', label: 'Roulette'},
      { value: 'Roxanne Simpson', label: 'Roxanne Simpson'},
      { value: 'Rumiko Fujikawa', label: 'Rumiko Fujikawa'},
      { value: 'Runaways', label: 'Runaways'},
      { value: 'Russian', label: 'Russian'},
      { value: 'S.H.I.E.L.D.', label: 'S.H.I.E.L.D.'},
      { value: 'Sabra', label: 'Sabra'},
      { value: 'Sabretooth', label: 'Sabretooth'},
      { value: 'Sage', label: 'Sage'},
      { value: 'Salem\'s Seven', label: 'Salem\'s Seven'},
      { value: 'Sally Floyd', label: 'Sally Floyd'},
      { value: 'Salo', label: 'Salo'},
      { value: 'Sandman', label: 'Sandman'},
      { value: 'Santa Claus', label: 'Santa Claus'},
      { value: 'Saracen', label: 'Saracen'},
      { value: 'Sasquatch', label: 'Sasquatch'},
      { value: 'Satana', label: 'Satana'},
      { value: 'Sauron', label: 'Sauron'},
      { value: 'Scalphunter', label: 'Scalphunter'},
      { value: 'Scarecrow', label: 'Scarecrow'},
      { value: 'Scarlet Spider', label: 'Scarlet Spider'},
      { value: 'Scarlet Witch', label: 'Scarlet Witch'},
      { value: 'Scorpion', label: 'Scorpion'},
      { value: 'Scourge', label: 'Scourge'},
      { value: 'Scrambler', label: 'Scrambler'},
      { value: 'Scream', label: 'Scream'},
      { value: 'Screwball', label: 'Screwball'},
      { value: 'Sebastian Shaw', label: 'Sebastian Shaw'},
      { value: 'Secret Warriors', label: 'Secret Warriors'},
      { value: 'Selene', label: 'Selene'},
      { value: 'Senator Kelly', label: 'Senator Kelly'},
      { value: 'Sentinel', label: 'Sentinel'},
      { value: 'Sentinels', label: 'Sentinels'},
      { value: 'Sentry', label: 'Sentry'},
      { value: 'Ser Duncan', label: 'Ser Duncan'},
      { value: 'Serpent Society', label: 'Serpent Society'},
      { value: 'Sersi', label: 'Sersi'},
      { value: 'Shadow King', label: 'Shadow King'},
      { value: 'Shadowcat', label: 'Shadowcat'},
      { value: 'Shadu the Shady', label: 'Shadu the Shady'},
      { value: 'Shalla-bal', label: 'Shalla-bal'},
      { value: 'Shaman', label: 'Shaman'},
      { value: 'Shane Yamada-Jones', label: 'Shane Yamada-Jones'},
      { value: 'Shang-Chi', label: 'Shang-Chi'},
      { value: 'Shanna the She-Devil', label: 'Shanna the She-Devil'},
      { value: 'Shape', label: 'Shape'},
      { value: 'Shard', label: 'Shard'},
      { value: 'Sharon Carter', label: 'Sharon Carter'},
      { value: 'Sharon Ventura', label: 'Sharon Ventura'},
      { value: 'Shatterstar', label: 'Shatterstar'},
      { value: 'She-Hulk', label: 'She-Hulk'},
      { value: 'Shen', label: 'Shen'},
      { value: 'Sheva Callister', label: 'Sheva Callister'},
      { value: 'Shi\'Ar', label: 'Shi\'Ar'},
      { value: 'Shinko Yamashiro', label: 'Shinko Yamashiro'},
      { value: 'Shinobi Shaw', label: 'Shinobi Shaw'},
      { value: 'Shiva', label: 'Shiva'},
      { value: 'Shiver Man', label: 'Shiver Man'},
      { value: 'Shocker', label: 'Shocker'},
      { value: 'Shockwave', label: 'Shockwave'},
      { value: 'Shooting Star', label: 'Shooting Star'},
      { value: 'Shotgun', label: 'Shotgun'},
      { value: 'Shriek', label: 'Shriek'},
      { value: 'Sif', label: 'Sif'},
      { value: 'Silhouette', label: 'Silhouette'},
      { value: 'Silk Fever', label: 'Silk Fever'},
      { value: 'Silver Centurion', label: 'Silver Centurion'},
      { value: 'Silver Fox', label: 'Silver Fox'},
      { value: 'Silver Sable', label: 'Silver Sable'},
      { value: 'Silver Samurai', label: 'Silver Samurai'},
      { value: 'Silver Surfer', label: 'Silver Surfer'},
      { value: 'Silverclaw', label: 'Silverclaw'},
      { value: 'Silvermane', label: 'Silvermane'},
      { value: 'Sin', label: 'Sin'},
      { value: 'Sinister Six', label: 'Sinister Six'},
      { value: 'Sir Ram', label: 'Sir Ram'},
      { value: 'Siren', label: 'Siren'},
      { value: 'Sister Grimm', label: 'Sister Grimm'},
      { value: 'Skaar', label: 'Skaar'},
      { value: 'Skin', label: 'Skin'},
      { value: 'Skreet', label: 'Skreet'},
      { value: 'Skrulls', label: 'Skrulls'},
      { value: 'Skullbuster', label: 'Skullbuster'},
      { value: 'Slapstick', label: 'Slapstick'},
      { value: 'Slayback', label: 'Slayback'},
      { value: 'Sleeper', label: 'Sleeper'},
      { value: 'Sleepwalker', label: 'Sleepwalker'},
      { value: 'Slipstream', label: 'Slipstream'},
      { value: 'Slyde', label: 'Slyde'},
      { value: 'Smasher', label: 'Smasher'},
      { value: 'Smiling Tiger', label: 'Smiling Tiger'},
      { value: 'Snowbird', label: 'Snowbird'},
      { value: 'Solo', label: 'Solo'},
      { value: 'Songbird', label: 'Songbird'},
      { value: 'Sons of the Tiger', label: 'Sons of the Tiger'},
      { value: 'Spacker Dave', label: 'Spacker Dave'},
      { value: 'Spectrum', label: 'Spectrum'},
      { value: 'Speed', label: 'Speed'},
      { value: 'Speed Demon', label: 'Speed Demon'},
      { value: 'Speedball', label: 'Speedball'},
      { value: 'Spencer Smythe', label: 'Spencer Smythe'},
      { value: 'Sphinx', label: 'Sphinx'},
      { value: 'Spider-dok', label: 'Spider-dok'},
      { value: 'Spider-Girl', label: 'Spider-Girl'},
      { value: 'Spider-Ham', label: 'Spider-Ham'},
      { value: 'Spider-Man', label: 'Spider-Man'},
      { value: 'Spider-Woman', label: 'Spider-Woman'},
      { value: 'Spiral', label: 'Spiral'},
      { value: 'Spirit', label: 'Spirit'},
      { value: 'Spitfire', label: 'Spitfire'},
      { value: 'Spot', label: 'Spot'},
      { value: 'Sprite', label: 'Sprite'},
      { value: 'Spyke', label: 'Spyke'},
      { value: 'Squadron Sinister', label: 'Squadron Sinister'},
      { value: 'Squadron Supreme', label: 'Squadron Supreme'},
      { value: 'Squirrel Girl', label: 'Squirrel Girl'},
      { value: 'Stacy X', label: 'Stacy X'},
      { value: 'Star Brand', label: 'Star Brand'},
      { value: 'Star-Lord', label: 'Star-Lord'},
      { value: 'Starbolt', label: 'Starbolt'},
      { value: 'Stardust', label: 'Stardust'},
      { value: 'Starfox', label: 'Starfox'},
      { value: 'Starhawk', label: 'Starhawk'},
      { value: 'Starjammers', label: 'Starjammers'},
      { value: 'Stark Industries', label: 'Stark Industries'},
      { value: 'Stature', label: 'Stature'},
      { value: 'Steel Serpent', label: 'Steel Serpent'},
      { value: 'Stellaris', label: 'Stellaris'},
      { value: 'Stepford Cuckoos', label: 'Stepford Cuckoos'},
      { value: 'Stephanie de la Spiroza', label: 'Stephanie de la Spiroza'},
      { value: 'Stephen Strange', label: 'Stephen Strange'},
      { value: 'Steve Rogers', label: 'Steve Rogers'},
      { value: 'Stick', label: 'Stick'},
      { value: 'Stilt-Man', label: 'Stilt-Man'},
      { value: 'Stingray', label: 'Stingray'},
      { value: 'Stone Men', label: 'Stone Men'},
      { value: 'Storm', label: 'Storm'},
      { value: 'Stranger', label: 'Stranger'},
      { value: 'Strong Guy', label: 'Strong Guy'},
      { value: 'Stryfe', label: 'Stryfe'},
      { value: 'Sub-Mariner', label: 'Sub-Mariner'},
      { value: 'Sue Storm', label: 'Sue Storm'},
      { value: 'Sugar Man', label: 'Sugar Man'},
      { value: 'Sumo', label: 'Sumo'},
      { value: 'Sunfire', label: 'Sunfire'},
      { value: 'Sunset Bain', label: 'Sunset Bain'},
      { value: 'Sunspot', label: 'Sunspot'},
      { value: 'Super Hero Squad', label: 'Super Hero Squad'},
      { value: 'Super-Adaptoid', label: 'Super-Adaptoid'},
      { value: 'Super-Skrull', label: 'Super-Skrull'},
      { value: 'Supernaut', label: 'Supernaut'},
      { value: 'Supreme Intelligence', label: 'Supreme Intelligence'},
      { value: 'Surge', label: 'Surge'},
      { value: 'Susan Delgado', label: 'Susan Delgado'},
      { value: 'Swarm', label: 'Swarm'},
      { value: 'Sway', label: 'Sway'},
      { value: 'Switch', label: 'Switch'},
      { value: 'Swordsman', label: 'Swordsman'},
      { value: 'Sym', label: 'Sym'},
      { value: 'Synch', label: 'Synch'},
      { value: 'T\'Challa', label: 'T\'Challa'},
      { value: 'Tag', label: 'Tag'},
      { value: 'Talisman', label: 'Talisman'},
      { value: 'Talkback', label: 'Talkback'},
      { value: 'Talon', label: 'Talon'},
      { value: 'Talos', label: 'Talos'},
      { value: 'Tana Nile', label: 'Tana Nile'},
      { value: 'Tarantula', label: 'Tarantula'},
      { value: 'Tarot', label: 'Tarot'},
      { value: 'Taskmaster', label: 'Taskmaster'},
      { value: 'Tattoo', label: 'Tattoo'},
      { value: 'Ted Forrester', label: 'Ted Forrester'},
      { value: 'Tempest', label: 'Tempest'},
      { value: 'Tenebrous', label: 'Tenebrous'},
      { value: 'Terrax', label: 'Terrax'},
      { value: 'Terror', label: 'Terror'},
      { value: 'Texas Twister', label: 'Texas Twister'},
      { value: 'Thaddeus Ross', label: 'Thaddeus Ross'},
      { value: 'Thanos', label: 'Thanos'},
      { value: 'The 198', label: 'The 198'},
      { value: 'The Anarchist', label: 'The Anarchist'},
      { value: 'The Call', label: 'The Call'},
      { value: 'The Captain', label: 'The Captain'},
      { value: 'The Enforcers', label: 'The Enforcers'},
      { value: 'The Executioner', label: 'The Executioner'},
      { value: 'The Fallen', label: 'The Fallen'},
      { value: 'The Fury', label: 'The Fury'},
      { value: 'The Hand', label: 'The Hand'},
      { value: 'The Hood', label: 'The Hood'},
      { value: 'The Howling Commandos', label: 'The Howling Commandos'},
      { value: 'The Hunter', label: 'The Hunter'},
      { value: 'The Initiative', label: 'The Initiative'},
      { value: 'The Leader', label: 'The Leader'},
      { value: 'The Liberteens', label: 'The Liberteens'},
      { value: 'The Liberty Legion', label: 'The Liberty Legion'},
      { value: 'The Order', label: 'The Order'},
      { value: 'The Phantom', label: 'The Phantom'},
      { value: 'The Professor', label: 'The Professor'},
      { value: 'The Renegades', label: 'The Renegades'},
      { value: 'The Santerians', label: 'The Santerians'},
      { value: 'The Shiver Man', label: 'The Shiver Man'},
      { value: 'The Spike', label: 'The Spike'},
      { value: 'The Stranger', label: 'The Stranger'},
      { value: 'The Twelve', label: 'The Twelve'},
      { value: 'The Watchers', label: 'The Watchers'},
      { value: 'Thena', label: 'Thena'},
      { value: 'Thing', label: 'Thing'},
      { value: 'Thor', label: 'Thor'},
      { value: 'Thor Girl', label: 'Thor Girl'},
      { value: 'Thunderball', label: 'Thunderball'},
      { value: 'Thunderbird', label: 'Thunderbird'},
      { value: 'Thunderbolt', label: 'Thunderbolt'},
      { value: 'Thunderbolt Ross', label: 'Thunderbolt Ross'},
      { value: 'Thunderbolts', label: 'Thunderbolts'},
      { value: 'Thundra', label: 'Thundra'},
      { value: 'Tiger Shark', label: 'Tiger Shark'},
      { value: 'Tiger\'s Beautiful Daughter', label: 'Tiger\'s Beautiful Daughter'},
      { value: 'Tigra', label: 'Tigra'},
      { value: 'Timeslip', label: 'Timeslip'},
      { value: 'Tinkerer', label: 'Tinkerer'},
      { value: 'Titania', label: 'Titania'},
      { value: 'Titanium Man', label: 'Titanium Man'},
      { value: 'Toad', label: 'Toad'},
      { value: 'Toad Men', label: 'Toad Men'},
      { value: 'Tomas', label: 'Tomas'},
      { value: 'Tombstone', label: 'Tombstone'},
      { value: 'Tomorrow Man', label: 'Tomorrow Man'},
      { value: 'Tony Stark', label: 'Tony Stark'},
      { value: 'Toro', label: 'Toro'},
      { value: 'Toxin', label: 'Toxin'},
      { value: 'Trauma', label: 'Trauma'},
      { value: 'Triathlon', label: 'Triathlon'},
      { value: 'Trish Tilby', label: 'Trish Tilby'},
      { value: 'Triton', label: 'Triton'},
      { value: 'True Believers', label: 'True Believers'},
      { value: 'Turbo', label: 'Turbo'},
      { value: 'Tusk', label: 'Tusk'},
      { value: 'Two-Gun Kid', label: 'Two-Gun Kid'},
      { value: 'Tyger Tiger', label: 'Tyger Tiger'},
      { value: 'Typhoid Mary', label: 'Typhoid Mary'},
      { value: 'Tyrannus', label: 'Tyrannus'},
      { value: 'U-Foes', label: 'U-Foes'},
      { value: 'U-Go Girl', label: 'U-Go Girl'},
      { value: 'U.S. Agent', label: 'U.S. Agent'},
      { value: 'Uatu The Watcher', label: 'Uatu The Watcher'},
      { value: 'Ulik', label: 'Ulik'},
      { value: 'Ultimate Spider-Man', label: 'Ultimate Spider-Man'},
      { value: 'Ultimates', label: 'Ultimates'},
      { value: 'Ultimatum', label: 'Ultimatum'},
      { value: 'Ultimo', label: 'Ultimo'},
      { value: 'Ultra-Adaptoid', label: 'Ultra-Adaptoid'},
      { value: 'Ultragirl', label: 'Ultragirl'},
      { value: 'Ultron', label: 'Ultron'},
      { value: 'Umar', label: 'Umar'},
      { value: 'Unicorn', label: 'Unicorn'},
      { value: 'Union Jack', label: 'Union Jack'},
      { value: 'Unus', label: 'Unus'},
      { value: 'Valeria Richards', label: 'Valeria Richards'},
      { value: 'Valkyrie', label: 'Valkyrie'},
      { value: 'Vampiro', label: 'Vampiro'},
      { value: 'Vance Astro', label: 'Vance Astro'},
      { value: 'Vanisher', label: 'Vanisher'},
      { value: 'Vapor', label: 'Vapor'},
      { value: 'Vargas', label: 'Vargas'},
      { value: 'Vector', label: 'Vector'},
      { value: 'Veda', label: 'Veda'},
      { value: 'Vengeance', label: 'Vengeance'},
      { value: 'Venom', label: 'Venom'},
      { value: 'Venus', label: 'Venus'},
      { value: 'Venus Dee Milo', label: 'Venus Dee Milo'},
      { value: 'Vermin', label: 'Vermin'},
      { value: 'Vertigo', label: 'Vertigo'},
      { value: 'Victor Mancha', label: 'Victor Mancha'},
      { value: 'Victor Von Doom', label: 'Victor Von Doom'},
      { value: 'Vin Gonzales', label: 'Vin Gonzales'},
      { value: 'Vindicator', label: 'Vindicator'},
      { value: 'Violations', label: 'Violations'},
      { value: 'Viper', label: 'Viper'},
      { value: 'Virginia Dare', label: 'Virginia Dare'},
      { value: 'Vision', label: 'Vision'},
      { value: 'Vivisector', label: 'Vivisector'},
      { value: 'Vulcan', label: 'Vulcan'},
      { value: 'Vulture', label: 'Vulture'},
      { value: 'Wallflower', label: 'Wallflower'},
      { value: 'Wallop', label: 'Wallop'},
      { value: 'Wallow', label: 'Wallow'},
      { value: 'War', label: 'War'},
      { value: 'War Machine', label: 'War Machine'},
      { value: 'Warbird', label: 'Warbird'},
      { value: 'Warbound', label: 'Warbound'},
      { value: 'Warhawk', label: 'Warhawk'},
      { value: 'Warlock', label: 'Warlock'},
      { value: 'Warpath', label: 'Warpath'},
      { value: 'Warren Worthington III', label: 'Warren Worthington III'},
      { value: 'Warstar', label: 'Warstar'},
      { value: 'Wasp', label: 'Wasp'},
      { value: 'Weapon Omega', label: 'Weapon Omega'},
      { value: 'Weapon X', label: 'Weapon X'},
      { value: 'Wendell Rand', label: 'Wendell Rand'},
      { value: 'Wendell Vaughn', label: 'Wendell Vaughn'},
      { value: 'Wendigo', label: 'Wendigo'},
      { value: 'Werewolf By Night', label: 'Werewolf By Night'},
      { value: 'Whiplash', label: 'Whiplash'},
      { value: 'Whirlwind', label: 'Whirlwind'},
      { value: 'Whistler', label: 'Whistler'},
      { value: 'White Queen', label: 'White Queen'},
      { value: 'White Tiger', label: 'White Tiger'},
      { value: 'Whizzer', label: 'Whizzer'},
      { value: 'Wiccan', label: 'Wiccan'},
      { value: 'Wild Child', label: 'Wild Child'},
      { value: 'Wild Pack', label: 'Wild Pack'},
      { value: 'Wildside', label: 'Wildside'},
      { value: 'William Stryker', label: 'William Stryker'},
      { value: 'Wilson Fisk', label: 'Wilson Fisk'},
      { value: 'Wind Dancer', label: 'Wind Dancer'},
      { value: 'Winter Soldier', label: 'Winter Soldier'},
      { value: 'Wither', label: 'Wither'},
      { value: 'Wolf Cub', label: 'Wolf Cub'},
      { value: 'Wolfpack', label: 'Wolfpack'},
      { value: 'Wolfsbane', label: 'Wolfsbane'},
      { value: 'Wolver-dok', label: 'Wolver-dok'},
      { value: 'Wolverine', label: 'Wolverine'},
      { value: 'Wonder Man', label: 'Wonder Man'},
      { value: 'Wong', label: 'Wong'},
      { value: 'Wraith', label: 'Wraith'},
      { value: 'Wrecker', label: 'Wrecker'},
      { value: 'Wrecking Crew', label: 'Wrecking Crew'},
      { value: 'X-23', label: 'X-23'},
      { value: 'X-51', label: 'X-51'},
      { value: 'X-Babies', label: 'X-Babies'},
      { value: 'X-Cutioner', label: 'X-Cutioner'},
      { value: 'X-Factor', label: 'X-Factor'},
      { value: 'X-Factor Investigations', label: 'X-Factor Investigations'},
      { value: 'X-Force', label: 'X-Force'},
      { value: 'X-Man', label: 'X-Man'},
      { value: 'X-Men', label: 'X-Men'},
      { value: 'X-Ray', label: 'X-Ray'},
      { value: 'X-Statix', label: 'X-Statix'},
      { value: 'X.S.E.', label: 'X.S.E.'},
      { value: 'Xavin', label: 'Xavin'},
      { value: 'Xorn', label: 'Xorn'},
      { value: 'Yellow Claw', label: 'Yellow Claw'},
      { value: 'Yellowjacket', label: 'Yellowjacket'},
      { value: 'Young Avengers', label: 'Young Avengers'},
      { value: 'Young X-Men', label: 'Young X-Men'},
      { value: 'Zaladane', label: 'Zaladane'},
      { value: 'Zaran', label: 'Zaran'},
      { value: 'Zarda', label: 'Zarda'},
      { value: 'Zarek', label: 'Zarek'},
      { value: 'Zeigeist', label: 'Zeigeist'},
      { value: 'Zemo', label: 'Zemo'},
      { value: 'Zodiak', label: 'Zodiak'},
      { value: 'Zombie', label: 'Zombie'},
      { value: 'Zuras', label: 'Zuras'},
      { value: 'Zzza', label: 'Zzza'}
    ];
    return( 
        <div className="fighterBlock">
          <Select
            name="form-field-name"
            value={this.state.selectValue} 
            className="selectah"
            options={options}
            onChange={this.updateValue}
          />
        </div>
    );
  }
});

module.exports = Fighter;